-- The DomainExpansionExecutable module is an executable generated by the CutsceneManager plugin.
-- This is a client-side executable, so it should be required through a locally handled system or Controller.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")

local DomainExpansionExecutable = {}

DomainExpansionExecutable.Enabled = true :: boolean
DomainExpansionExecutable.CutsceneConnection = nil :: Tween
DomainExpansionExecutable.CutsceneHashmap = {
	["Waypoint1"] = {
		["iteration"] = "1",
		["easingStyle"] = "Linear",
		["tilt"] = "0",
		["fov"] = "70",
		["instance"] = "-113.796867, 6.70196438, -84.289711, 0, 0, 1, 0, 1, -0, -1, 0, 0",
		["duration"] = "0",
		["delay"] = "0",
		["easingDirection"] = "In",
	},
	["Waypoint2"] = {
		["iteration"] = "2",
		["easingStyle"] = "Cubic",
		["tilt"] = "0",
		["fov"] = "70",
		["instance"] = "-113.796867, 3.70074248, -84.289711, 0, 0, 1, 0, 1, -0, -1, 0, 0",
		["duration"] = "3.5",
		["delay"] = "0",
		["easingDirection"] = "Out",
	},
	-- ["Waypoint3"] = {
	-- 	["iteration"] = "3",
	-- 	["easingStyle"] = "Cubic",
	-- 	["tilt"] = "0",
	-- 	["fov"] = "70",
	-- 	["instance"] = "-115.88726, 4.31216526, -84.2881927, -0.003254232, -0.138401151, 0.990371406, 0, 0.990376651, 0.138401836, -0.999994755, 0.000450391672, -0.00322291534",
	-- 	["duration"] = "1.5",
	-- 	["delay"] = "0",
	-- 	["easingDirection"] = "Out",
	-- },
	["Waypoint3"] = {
		["iteration"] = "3",
		["easingStyle"] = "Cubic",
		["tilt"] = "0",
		["fov"] = "70",
		["instance"] = "-91.8989639, 3.70074248, -84.289711, 0, 0, 1, 0, 1, -0, -1, 0, 0",
		["duration"] = "2.5",
		["delay"] = "0",
		["easingDirection"] = "Out",
	},
} :: CutsceneIndex

--- Iterates through hashmap and plays the cutscene.
--- @param hashmap CutsceneIndex The target hashmap
function DomainExpansionExecutable:Play()
	local waypointModel = ReplicatedStorage.GameAssets.CutsceneWaypoints.DomainExpansionWaypoints:Clone()
	waypointModel:PivotTo(Players.LocalPlayer.Character.HumanoidRootPart.CFrame)
	waypointModel.Parent = workspace.IgnoreInstances.MagicSpells

	DomainExpansionExecutable.Enabled = true

	local waypointTotal = 0

	local hashmap = self.CutsceneHashmap

	for _, _ in hashmap do
		waypointTotal += 1
	end

	local previousCameraType = workspace.CurrentCamera.CameraType
	local previousCameraFieldOfView = workspace.CurrentCamera.FieldOfView

	workspace.CurrentCamera.CameraType = Enum.CameraType.Scriptable

	for i = 1, waypointTotal do
		local waypointData = hashmap["Waypoint" .. i]
		local tweenInfo = TweenInfo.new(
			tonumber(waypointData.duration),
			Enum.EasingStyle[waypointData.easingStyle],
			Enum.EasingDirection[waypointData.easingDirection],
			0,
			false,
			tonumber(waypointData.delay)
		)

		local finalCameraTilt = if waypointData.tilt == 0
			then 0
			else math.rad(waypointData.tilt) - workspace.CurrentCamera.CFrame:ToOrientation()
		print(finalCameraTilt)
		local finalCameraCFrame = waypointModel[tostring(i)].CFrame * CFrame.Angles(0, 0, finalCameraTilt)

		self.CutsceneConnection = TweenService:Create(workspace.CurrentCamera, tweenInfo, {
			CFrame = finalCameraCFrame,
			FieldOfView = tonumber(waypointData.fov),
		})

		self.CutsceneConnection:Play()
		self.CutsceneConnection.Completed:Wait()

		if not self.Enabled then
			break
		end
	end

	workspace.CurrentCamera.CameraType = previousCameraType
	workspace.CurrentCamera.FieldOfView = previousCameraFieldOfView
end

--- Stops any existing cutscenes that resembles the passed hashmap.
--- @param hashmap CutsceneIndex The target hashmap.
function DomainExpansionExecutable:Stop(hashmap: CutsceneIndex)
	if hashmap ~= DomainExpansionExecutable.CutsceneHashmap then
		return
	end

	DomainExpansionExecutable.Enabled = false

	if DomainExpansionExecutable.CutsceneConnection then
		DomainExpansionExecutable.CutsceneConnection:Cancel()
	end
end

export type DomainExpansionExecutable = typeof(DomainExpansionExecutable)

export type CutsceneIndex = {
	[string]: {
		iteration: number,
		instance: BasePart,
		fov: number,
		tilt: number,
		delay: number,
		duration: number,
		easingStyle: string,
		easingDirection: string,
	},
}

return DomainExpansionExecutable :: DomainExpansionExecutable
