-- The SusanooExecutable module is an executable generated by the CutsceneManager plugin.
-- This is a client-side executable, so it should be required through a locally handled system or Controller.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")
local Players = game:GetService("Players")

local SusanooExecutable = {}

SusanooExecutable.Enabled = true :: boolean
SusanooExecutable.CutsceneConnection = nil :: Tween
SusanooExecutable.CutsceneHashmap = {
	["Waypoint2"] = {
		["easingDirection"] = "InOut",
		["tilt"] = "11",
		["easingStyle"] = "Quad",
		["fov"] = "90",
		["instance"] = "-7.47974634, 3.94599366, 9.38573647, -0.924528182, -0.00139979273, -0.381119072, 0, 0.999995172, -0.00367346406, 0.38112089, -0.00339598395, -0.92452389",
		["duration"] = "2",
		["delay"] = "0",
		["iteration"] = "2",
	},
	["Waypoint1"] = {
		["easingDirection"] = "In",
		["tilt"] = "0",
		["easingStyle"] = "Linear",
		["fov"] = "80",
		["instance"] = "-3.86300993, 3.03434539, 10.5573931, -0.692847073, 0.282439679, 0.663468778, 0, 0.920098484, -0.391687304, -0.721084595, -0.271379381, -0.637487471",
		["duration"] = "0",
		["delay"] = "0",
		["iteration"] = "1",
	},
} :: CutsceneIndex

--- Iterates through hashmap and plays the cutscene.
function SusanooExecutable:Play()
	local waypointModel = ReplicatedStorage.GameAssets.CutsceneWaypoints.SusanooWaypoints:Clone()
	waypointModel:PivotTo(Players.LocalPlayer.Character.HumanoidRootPart.CFrame)
	waypointModel.Parent = workspace.IgnoreInstances.MagicSpells

	SusanooExecutable.Enabled = true

	local waypointTotal = 0

	local hashmap = self.CutsceneHashmap

	for _, _ in hashmap do
		waypointTotal += 1
	end

	local previousCameraType = workspace.CurrentCamera.CameraType
	local previousCameraFieldOfView = workspace.CurrentCamera.FieldOfView

	for i = 1, waypointTotal do
		local waypointData = hashmap["Waypoint" .. i]
		local tweenInfo = TweenInfo.new(
			tonumber(waypointData.duration),
			Enum.EasingStyle[waypointData.easingStyle],
			Enum.EasingDirection[waypointData.easingDirection],
			0,
			false,
			tonumber(waypointData.delay)
		)

		local finalCameraTilt = if waypointData.tilt == 0
			then 0
			else math.rad(waypointData.tilt) - workspace.CurrentCamera.CFrame:ToOrientation()
		local finalCameraCFrame = waypointModel[tostring(i)].CFrame * CFrame.Angles(0, 0, finalCameraTilt)

		SusanooExecutable.CutsceneConnection = TweenService:Create(workspace.CurrentCamera, tweenInfo, {
			CFrame = finalCameraCFrame,
			FieldOfView = tonumber(waypointData.fov),
		})

		workspace.CurrentCamera.CameraType = Enum.CameraType.Scriptable

		SusanooExecutable.CutsceneConnection:Play()
		SusanooExecutable.CutsceneConnection.Completed:Wait()

		if not SusanooExecutable.Enabled then
			break
		end
	end

	workspace.CurrentCamera.CameraType = previousCameraType
	workspace.CurrentCamera.FieldOfView = previousCameraFieldOfView
end

--- Stops any existing cutscenes that resembles the passed hashmap.
function SusanooExecutable:Stop(hashmap: CutsceneIndex)
	if hashmap ~= SusanooExecutable.CutsceneHashmap then
		return
	end

	SusanooExecutable.Enabled = false
	if SusanooExecutable.CutsceneConnection then
		SusanooExecutable.CutsceneConnection:Cancel()
	end
end

export type SusanooExecutable = typeof(SusanooExecutable)

export type CutsceneIndex = {
	[string]: {
		iteration: number,
		instance: BasePart,
		fov: number,
		tilt: number,
		delay: number,
		duration: number,
		easingStyle: string,
		easingDirection: string,
	},
}

return SusanooExecutable :: SusanooExecutable
